#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

mpirun --oversubscribe -np $1 $DIR/print_nodes
if [ ! -d gdbgui-mpi ]; then
    mkdir gdbgui-mpi
fi
mv nodes_name gdbgui-mpi/
mpirun --oversubscribe -np $1 launch_gdb_server ${@:2} # &
rm nodes_name
#python -m gdbgui-mpi


