GDBGUI=../../gdbgui/backend.py

hello: hello.cpp
	g++ hello.cpp -o hello_cpp.a -std=c++11 -g
	@echo Run with gdbgui: gdbgui --args hello_cpp.a

linked_list: linked_list.cpp
	g++ linked_list.cpp -o linked_list_cpp.a -std=c++11 -g
	@echo Run with gdbgui: gdbgui --args linked_list_cpp.a

smart_ptr_demo: smart_ptr_demo.cpp
	g++ smart_ptr_demo.cpp -o smart_ptr_demo_cpp.a -std=c++11 -g
	@echo Run with gdbgui: gdbgui --args smart_ptr_demo_cpp.a

sin: sin.cpp
	g++ sin.cpp -o sin_cpp.a -std=c++11 -g
	@echo Run with gdbgui: gdbgui --args sin_cpp.a
